Change DeformationFieldTransforma and PositionFieldTransform to use Compsite<T>
imglib/imglib2-realtransform pull request #42
Opened 2022-08-16 21:19 UTC by cmhulbert

2022-08-16 21:21 UTC, cmhulbert commented
@bogovicj let me know what you think. It's in draft for now, but I think I implemented everything in #41

2022-08-17 16:07 UTC, bogovicj requested changes
A couple minor things + we may want to change the implementation in places.

2022-08-20 01:35 UTC, axtimwalde commented on src/main/java/net/imglib2/realtransform/DeformationFieldTransform.java
> +			target.setPosition( comp.get( d ).getRealDouble() + source.getDoublePosition( d ), d );
Good point!  Done.

2022-08-20 01:35 UTC, axtimwalde commented on src/main/java/net/imglib2/realtransform/PositionFieldTransform.java
> +		for ( int d = 0; d < target.length; d++ )
Nice! Done.

2022-08-20 01:36 UTC, axtimwalde commented on src/main/java/net/imglib2/realtransform/PositionFieldTransform.java
> +	protected final RealRandomAccess< RealComposite< T > > positionAccesses;
Or access because inherited by displacementfields, done.

2022-08-23 18:36 UTC, bogovicj commented
I'd like to add some tests that check

* `PositionFieldTransform`s with  `numSourceDimensions() != numTargetDimensions()`
* applying these transforms for points of higher dimensionality

2022-09-01 20:07 UTC, bogovicj approved these changes

2022-09-16 18:35 UTC, merged